---
- After Effects
- Blender
- Cinema 4D
- Final Cut Pro
- Houdini
- Illustrator
- InDesign
- Maya
- Microsoft Excel
- Microsoft Word
- OMF
- PDF
- Photoshop
- Powerpoint
- Premiere
- Pro Tools
- Pro Tools (5+)
- Pro Tools 10
- Pro Tools 12.5
- Pro Tools 4.3
- Pro Tools 6.9
- Pro Tools 7.1
- Pro Tools 7.2
- Pro Tools 7.3
- Pro Tools 7.4
- Pro Tools 8
- Pro Tools 9.0
- Quark
