---
- Architectural Services
- Asset Management
- AXN - Ad Sales - Taiwan
- AXN - Creative Services - Taiwan
- AXN - Marketing - Taiwan
- AXN - Original Productions - Taiwan
- AXN - Programming - Taiwan
- AXN - TITV - Taiwan
- China Production
- cineSHARE + Archive
- CMDG Airlines
- CMDG Client Ops
- CMDG CODHE
- CMDG Dubbing
- CMDG GPS
- CMDG Localization
- CMDG Production Ops
- CMDG Trailers
- CMDG TVI
- CSC Media Group
- Corporate Communications
- DCS
- DCS Ancillary Assets
- DCS Editorial Services
- DCS Localization - Airlines Only
- DCS Localization - Home Entertainment
- DCS Localization - Television
- DCS Localization - Theatrical
- DCS Systems & Workflow
- DCS Technical Operations
- DCS Title Stewardship
- Digital Content Technologies
- Digital Media Group
- Embassy Row
- Funimation
- Imageworks
- Intl Post Production
- IT - APAC
- IT - Corporate
- IT - SPHE
- Jeopardy! Post Production
- MPG Affirm Films
- MPG AV Marketing Post Production
- MPG Consumer Marketing
- MPG Consumer Products
- MPG Creative Content
- MPG Creative Finishing
- MPG Digital Marketing
- MPG Dom Digital Marketing
- MPG Exhibitor Relations
- MPG Field Exploitation
- MPG Global Client Services
- MPG International Productions
- MPG International Promotions
- MPG Interplan
- MPG INT Sales
- MPG Intl Digital Marketing
- MPG Marketing
- MPG Marketing Clearances
- MPG Marketing – China
- MPG Partner - MGM
- MPG Partnership Portal
- MPG Photo
- MPG Print
- MPG Production – China
- MPG Publicity
- MPG Repertory Servicing
- MPG SAML
- MPG Sony Pictures Classics
- MPG Sony Pictures Virtual Reality
- MPG SPRI AV Script
- MPG Territories
- Music Affairs
- Music Creative Affairs
- SAML
- Sony Pictures Content Licensing
- SPC
- SPE Connect Admin
- SPHE Content Creation
- SPHE Content Development
- SPHE Creative Advertising
- SPHE Global Digital Operations
- SPHE Marketing
- SPHE Photo
- SPHE Print
- SPR AsiaPac
- SPT China
- SPT Crackle Content Operations - LatAm
- SPT Crackle Content Operations - US
- SPT Crackle Product
- SPT DAM - Dominic White
- SPT DAM - Johnnie Monico
- SPT DAM - Lana Hayden
- SPT DAM - Melissa Moshe
- SPT Design
- SPT Digital Asset Management
- SPT Digital Networks
- SPT Events
- SPT Formats Marketing
- SPT Franchise Marketing
- SPT Intl Marketing - Networks
- SPT Intl Productions
- SPT LatAm Acquisitions
- SPT Marketing
- SPT Marketing - Ad Sales
- SPT Marketing - Syndication
- SPT Media Relations
- SPT Networks - Ad Sales - Asia
- SPT Networks - Affiliate Marketing - Asia
- SPT Networks - Asian Content - Asia
- SPT Networks - Content Services - Asia
- SPT Networks - Corporate - Asia
- SPT Networks - EC Marketing - Asia
- SPT Networks - EC Public Relations - Asia
- SPT Networks - English Content - Asia
- SPT Networks - LatAm
- SPT Networks - Original Productions - Asia
- SPT Networks - Original Programming - LatAm
- SPT Networks - Original Programming
- SPT Networks - Research - Asia
- SPT Networks - Sports - Singapore
- SPT Networks Asia - AXN
- SPT Networks Asia - English Content
- SPT Networks Asia - ONE
- SPT Networks Operations - Hungary
- SPT Networks Operations - UK
- SPT On Air
- SPT Photo
- SPT Post Production
- SPT Screener
- SPT US Networks
- SPTL Engineering
- SPTL Operations
- SPWA Ad Pub
- Stock Footage
- Studio Archives
- UNISPHE Australia
- VFX Asset Reuse Repository
- Wheel of Fortune Photo
- Wheel of Fortune Post Production
