---
- 11 (Discrete)
- 11+3 (Discrete)
- 11.1 (Discrete)
- 12+1 (Discrete)
- 12+2 (Discrete)
- 4+2 (Discrete)
- 5+3 (Discrete)
- 5.0 (Discrete)
- 5.1 (Discrete)
- 5.1 Discreet + Stereo Mix Broadcast
- 5.1 (Discreet) Broadcast
- 5.1 / Lt-Rt (Discrete)
- 5.1 Discrete + Stereo Comp
- 6+1 (Discrete)
- 6+2 (Discrete)
- 6.1 (Discrete)
- 7.1 (Discrete)
- 8+2 (Discrete)
- 9.1 (Discrete)
- Atmos
- Auro
- DTS 6 Track
- DTS X
- Dolby A Stereo
- Dolby EX (6.1)
- Dolby SR Stereo - SVA
- Dolby SRD 6 Track
- IMAX 12.0
- IMAX 5.0
- LCR (3.0) (Discrete)
- LCRS (4.0) (Discrete)
- Lt-Rt (Dolby Surround)
- Mono
- Mono Comp (Mix)
- Mono Comp (Mix) + Split Track
- No Audio (MOS)
- Production Audio
- SDDS 6 Track
- SDDS 8 Track
- Split Track
- Standard Stereo
- Stereo Comp (Mix)
- Stereo Comp (Mix) + Split Track
- Stereo Comp (Mix) Broadcast
- Ultra Stereo
