---
- Audience
- Back Surround Left
- Back Surround Right
- Center
- Center Front
- Center Rear
- Dialogue - Interview
- Dialogue - Show
- Dialogue Track
- Foreign Language Track
- Laugh Track
- Left
- Left Surround
- LFE
- LT
- MOS
- Mix Minus Music
- Mix Minus VO
- Mono Comp (Mix)
- Music
- Production Audio
- Right
- Right Surround
- RT
- Sound Effects
- Sound on Tape
- Special Effects
- Stereo Comp (Mix)-L
- Stereo Comp (Mix)-R
- Stereo M&E
- Voice Over Track
