---
- "000 - Sony Studio Lot"
- "001 - Colonnade"
- "002 - Washington Row"
- "003 - Cutting Building #3"
- "004 - Poitier (Sidney)"
- "006 - Rooney (Mickey)"
- "007 - Keaton (Buster)"
- "008 - Sound Building"
- "011 - Kelly (Gene)"
- "014 - Burns (George)"
- "016 - Astaire (Fred)"
- "020 - Gable (Clark)"
- "025 - Art Dept. & Commissary"
- "026 - Sound Recording Complex"
- "026A - Cary Grant Theatre"
- "029 - Capra (Frank)"
- "030 - Young (Robert)"
- "033B - Stage #07"
- "033A - Stage #08"
- "033C - Stage #09"
- "034 - Stage #10 (North)"
- "035 - Garland (Judy)"
- "036 - Stage #11"
- "037 - Stage #12"
- "038 - Stage #14"
- "039 - Lean (David)"
- "048 - Power Plant #2"
- "050 - Harry Cohn"
- "051 - Jack Cohn"
- "052 - Transportation"
- "057 - Dubbing # 15"
- "064 - Loy (Myrna)"
- "065 - Crawford (Joan)"
- "066 - Tracy (Spencer)"
- "067 - Stage #15"
- "069 - Stage #30"
- "070 - Durante (Jimmy)"
- "071 - Heidelberg"
- "073 - Stage #05"
- "074 - Stage #03"
- "075 - Stage #06"
- "081 - Grip's Storage"
- "093 - Scenic Art Building"
- "095 - Stage #21"
- "096 - Stage #22"
- "101 - Autry (Gene)"
- "102 - Stage #23"
- "103 - Stage #24"
- "115 - Hepburn (Katharine)"
- "118 - Set Lighting"
- "128 - Power Plant 03"
- "129 - Stage #25"
- "130 - Stage #26"
- "131 - Stage #27"
- "132 - Stage #28"
- "136 - Culver Parking Structure"
- "139 - Thalberg (Irving)"
- "159 - Garbo (Greta)"
- "160 - Barrymore (Lionel)"
- "164 - Scene Dock #05"
- "200 - Stewart (Jimmy)"
- "201 - Overland Structure"
- "205 - Thalberg Annex"
- "207 - Mailroom & Logistics Bldg"
- "210 – Studio Support Building"
- "220 – Production Services Building"
- "230 – Akio Morita"
- "300 - Westend Trailers"
- "500 - SPP - Sony Pictures Plaza"
- "502 - Corporate Pointe"
- "506 - 3830 Clarington"
- "507 - Bowtruss (Game Show Ntwk)"
- "508 - Child Care Center"
- "509 - 10003 Washington"
- "613 - Smith Building"
- "615 - TCSOB (Culver Office)"
- "616 - TCSOB Corner Building"
- "617 - TCSOB North"
- "620 - Meralta Plaza"
- "632 - Apple St. Warehouse"
- "636 - 8600 Hayden Ii"
- "642 - Alla Rd Warehouse"
- "653 - 5933 Slauson"
- "904 - NY - 226 West 26Th"
- "908 - NY - 150 Roger Ave (Inwood)"
- "909 - NY - 550 Madison Ave"
- "2300 - BRA - Plaza Centenario - Sao Paulo"
- "3865 - RUS - 21 Stanislavskogo St"
- "G-1 - Overland Guard Gate"
