---
- 3D HD_ProRes 422 HQ/220Mbps + PCM/Uncompressed_QT
- 3D MP4 1080p
- 4K HDR ProRes
- 4K SDR ProRes
- HD_ProRes 422 HQ/220Mbps + PCM/Uncompressed_QT
- MP4 1080p
- MP4 1500 Kbps
- MP4 720p
- Non Standard Spec
- SD_MPEG-2 PS/15Mbps + M1L2/224kbps
- SD_MPEG-2 PS/8Mbps + M1L2/224kbps
- SD_ProRes 422 HQ/60Mbps + PCM/Uncompressed_QT
- SD_WMV-9/1372kbps + WMA9.1/128kbps
- WMV 850 Kbps
