---
Abkhazian: abk
Afghan/Pashtu: pus
Afrikaans: afr
Albanian: sqi
Amharic: amh
Arabic: ara
Azeri/Azerbaijan: aze
Bangla/Bengali: ben
Bhojpuri: bho
Belgium Dual: !nil
Bosnian: bos
Bulgarian: bul
Burmese: mya
Catalan: cat
Chinese: zho
Chinese (Simplified): zho
Chinese (Traditional): zho
Chinese (Traditional – Cantonese): zho
Corsican: cos
Croatian: hrv
Czech: ces
Danish: Danish
Dutch: nld
Dutch (Belgium): nld
Dutch (Flemish): nld
Dutch (Netherlands): nld
Dzongkha: dzo
English: eng
English (AU): eng
English (UK): eng
English (US): eng
Estonian: est
Faroese: fao
Finnish: fin
French: fra
French (Belgium): fra
French (Canadian): fra
French (Parisian): fra
French (Swiss): fra
French (Middle East): fra
Gaelic: gla
Gaelic (Irish): gla
Gaelic (Scots): gla
Georgian: kat
German: deu
German (Austrian): deu
German (German): deu
German (Swiss): gsw
Greek: ell
Hebrew: ell
Hindi: hin
Hungarian: hun
Icelandic: isl
Indonesian: ind
Inuktitut: iku
Italian: ita
Japanese: jpn
Kannada: kan
Karakalpak: kaa
Kazakh: kaz
Khmer: khm
Korean: kor
Kurdish: kur
Kyrgyz: kir
Lao: Lao
Latvia Dual: lav
Latvian: lav
Lebanon Dual: lav
Lithuanian: lit
Macedonian: mkd
Malay: msa
Malayalam: mal
Maori: mri
Marathi: mar
Mongolian: mon
Nauvhal: !nil
Nepali: nep
None: !nil
Northern Sotho: nso
Norwegian: nno
Not Texted: !nil
Oriya: ori
Persian/Farsi: fas
Polish: pol
Portuguese: por
Portuguese (Brazil): por
Portuguese (Portugal): por
Punjabi: pan
Romanian: ron
Romany: rom
Russian: rus
Russian (Ukraine): rus
Samoan: smo
Serbian: srp
Serbo-Croatian: hrv
Sindhi: snd
Sinhalese: sin
Slovak: slk
Slovene: slv
Slovenian: slv
Somali: som
Spanish: spa
Spanish (Argentinean): spa
Spanish (Castilian): spa
Spanish (Chilean): spa
Spanish (Colombian): spa
Spanish (Cuban): spa
Spanish (Latin Am): spa
Spanish (Mexican): spa
Spanish (Puerto Rican): spa
Swahili: swa
Swedish: swe
Tagalog: tgl
Tamil: tam
Telugu: tgl
Thai: tha
Tibetan: bod
Turkish: tur
Ukrainian: ukr
Urdu: urd
Uzbek: uzb
Vietnamese: vie
Welsh: cym
Yiddish: yid
Zulu: zul
