---
- Asset Management
- Corporate
- Corporate Technology Development
- Content Management and Distribution Group
- Funimation
- Motion Picture Group
- SPDP Colorworks
- SPDP Imageworks
- SPDP Post Media Center
- SPDP Sony Pictures Animation
- SPDP Sound
- SPDP Stock Footage
- SPT Crackle
- SPT Crackle Latin America
- SPT Networks
- SPT Prod Domestic
- SPT Prod Intl
- SPT Sales
- Sony Pictures Home Entertainment
