---
-
  name: 'Africa'
  territories: [
    'Algeria',
    'Angola',
    'Benin',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Cameroon',
    'Canary Islands',
    'Cape Verde',
    'Central African Republic',
    'Chad',
    'Comoros',
    'Congo, Democratic Republic of (Zaire)',
    'Congo, Republic of',
    'Djibouti',
    'Egypt',
    'Equatorial Guinea',
    'Eritrea',
    'Ethiopia',
    'Gabon',
    'Gambia',
    'Ghana',
    'Guinea',
    'Guinea-Bissau',
    'Ivory Coast',
    'Kenya',
    'Lesotho',
    'Liberia',
    'Libya',
    'Madagascar',
    'Madeira',
    'Malawi',
    'Mali',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Niger',
    'Nigeria',
    'Reunion',
    'Rwanda',
    'Sao Tome & Principe',
    'Senegal',
    'Seychelles',
    'Sierra Leone',
    'Somalia',
    'South Africa, Republic of',
    'St. Helena',
    'Sudan',
    'Swaziland',
    'Tanzania',
    'Togo',
    'Tunisia',
    'Uganda',
    'Western Sahara',
    'Zambia',
    'Zimbabwe',
  ]
-
  name: 'Asia'
  territories: [
    'Afghanistan',
    'Bangladesh',
    'Bhutan',
    'Brunei',
    'Cambodia',
    'China',
    'East Timor',
    'Hong Kong',
    'India',
    'Indonesia',
    'Japan',
    'Korea, North',
    'Korea, South',
    'Laos',
    'Macau',
    'Malaysia',
    'Maldives',
    'Mongolia',
    'Myanmar',
    'Nepal',
    'Pakistan',
    'Philippines',
    'Singapore',
    'Sri Lanka',
    'Taiwan',
    'Thailand',
    'Vietnam',
  ]
-
  name: 'Caribbean'
  territories: [
    'Anguilla',
    'Antigua & Barbuda',
    'Aruba',
    'Bahamas',
    'Barbados',
    'Bermuda',
    'Bonaire',
    'Cayman Islands',
    'Cuba',
    'Curacao',
    'Dominica',
    'Dominican Republic',
    'Grenada',
    'Guadeloupe',
    'Haiti',
    'Jamaica',
    'Martinique',
    'Montserrat',
    'Puerto Rico',
    'Saba',
    'St. Eustatius',
    'St. Kitts-Nevis',
    'St. Lucia',
    'St. Maarten',
    'St. Martin',
    'St. Vincent & Grenadines',
    'Trinidad & Tobago',
    'Turks & Caicos',
    'Virgin Islands, British',
    'Virgin Islands, U.S.',
  ]
-
  name: 'Central America'
  territories: [
    'Belize',
    'Costa Rica',
    'El Salvador',
    'Guatemala',
    'Honduras',
    'Mexico',
    'Nicaragua',
    'Panama',
  ]
-
  name: 'Europe, Eastern'
  territories: [
    'Albania',
    'Armenia',
    'Azerbaijan',
    'Belarus',
    'Bosnia/Herzegovina',
    'Bulgaria',
    'Croatia',
    'Czech Republic',
    'Estonia',
    'Georgia',
    'Hungary',
    'Kazakhstan',
    'Kosovo',
    'Kyrgyzstan',
    'Latvia',
    'Lithuania',
    'Macedonia',
    'Moldova',
    'Montenegro',
    'Poland',
    'Romania',
    'Russia',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Tajikistan',
    'Turkmenistan',
    'Ukraine',
    'Uzbekistan',
  ]
-
  name: 'Europe, Western'
  territories: [
    'Andorra',
    'Austria',
    'Belgium',
    'Cyprus',
    'Denmark',
    'Finland',
    'France',
    'French Polynesia',
    'Germany',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Iceland',
    'Ireland',
    'Italy',
    'Liechtenstein',
    'Luxembourg',
    'Malta',
    'Monaco',
    'Netherlands',
    'New Caledonia',
    'Norway',
    'Portugal',
    'Spain',
    'St. Pierre & Miquelon',
    'Sweden',
    'Switzerland',
    'Turkey',
    'United Kingdom',
    'Wallis & Futuna',
  ]
-
  name: 'Middle East'
  territories: [
    'Bahrain',
    'Iran',
    'Iraq',
    'Israel',
    'Jordan',
    'Kuwait',
    'Lebanon',
    'Oman',
    'Qatar',
    'Saudi Arabia',
    'Syria',
    'United Arab Emirates',
    'Yemen, Republic of',
  ]
-
  name: 'North America'
  territories: [
    'American Samoa',
    'Canada',
    'Guam',
    'Marshall Islands',
    'Micronesia, Federated States Of',
    'Northern Mariana Islands',
    'Palau',
    'Quebec',
    'U.S.',
  ]
-
  name: 'Oceania'
  territories: [
    'Australia',
    'Cook Islands',
    'Fiji',
    'Kiribati',
    'Nauru',
    'New Zealand',
    'Niue Island',
    'Papua New Guinea',
    'Solomon Islands',
    'Tonga',
    'Tuvalu',
    'Vanuatu',
    'Western Samoa',
  ]
-
  name: 'South America'
  territories: [
    'Argentina',
    'Bolivia',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'French Guiana',
    'Guyana',
    'Paraguay',
    'Peru',
    'Surinam',
    'Uruguay',
    'Venezuela',
  ]
